name = "Create Aeronautics: Grand Alps"
author = "ZAPMasterBuilder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97673f175432386c76fd2991f53918b85b699376b3bf78093526c649afb1802d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
