name = "Create Aeronautics: Grand Alps"
author = "ZAPMasterBuilder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ddc176918b5dd6648d03c9cedee60013c7d32b373898b01b0df2af097f52a21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
